channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.26.4
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.13.1
name: mlflow-env
